export enum AUTHTYPE {
    SET_USER = 'AUTH_SET_USER',
    SIGN_OUT = 'AUTH_SIGN_OUT',
    SET_LOADING = 'AUTH_SET_LOADING',
    SET_ERROR = 'AUTH_SET_ERROR',
    NEED_VERIFICATION = 'AUTH_NEED_VERIFICATION',
    SET_SUCCESS = 'AUTH_SET_SUCCESS',
}
