export enum AUTH_TYPE {
    SET_USER = 'AUTH_SET_USER',
    SIGN_OUT = 'AUTH_SIGN_OUT',
    SET_LOADING = 'AUTH_SET_LOADING',
    SET_ERROR = 'AUTH_SET_ERROR',
    NEED_VERIFICATION = 'AUTH_NEED_VERIFICATION',
    SET_SUCCESS = 'AUTH_SET_SUCCESS',
}

// export const AUTH_SET_USER = 'AUTH_SET_USER';
// export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT'
// export const AUTH_SET_LOADING = 'AUTH_SET_LOADING'
// export const AUTH_SET_ERROR = 'AUTH_SET_ERROR'
// export const AUTH_NEED_VERIFICATION = 'AUTH_NEED_VERIFICATION'
// export const AUTH_SET_SUCCESS = 'AUTH_SET_SUCCESS'
