export enum HABILIDADES_TYPE {
   SET_HABILIDADES = 'HABILIDADES_SET_HABILIDADES',
   SET_LOADING = 'HABILIDADES_SET_LOADING',
   SET_ERROR = 'HABILIDADES_SET_ERROR',
   SET_SUCCESS = 'HABILIDADES_SET_SUCCESS',
   SET_PAGACTUAL = 'HABILIDADES_SET_PAGACTUAL',
}
