export enum PROYECTOS_TYPE {
   SET_PROYECTOS = 'PROYECTOS_SET_PROYECTOS',
   SET_LOADING = 'PROYECTOS_SET_LOADING',
   SET_ERROR = 'PROYECTOS_SET_ERROR',
   SET_SUCCESS = 'PROYECTOS_SET_SUCCESS',
   SET_PAGACTUAL = 'PROYECTOS_SET_PAGACTUAL',
}
